### ISSUE TITLE
No padding on some devices.

### ISSUE THREAD

**Issue by alashow** [vikramkakkar/SublimeNavigationView#11]
On Huawei 3C (Android version 4.2.2) I got like this weird look:
![sc 1](https://dotjpg.co/bP1o.jpg)

**Comment by vikramkakkar** [comment]
Its fixed with the latest commit on `dev` branch.

This is an issue I haven't encountered in a while. I first saw this while working on another project. The fix was to read padding values before the call to `setBackground(Drawable)` and then set the padding again: [Link](https://github.com/vikramkakkar/SublimeNavigationView/blob/dev/sublimenavigationviewlibrary/src/main/java/com/appeaser/sublimenavigationviewlibrary/SUtils.java#L17).

**Comment by gnuhel** [comment]
@vikramkakkar Hi. could you please release a new version with the new changes? Or is there a way to get the latest build with gradle? Thanks

**Comment by vikramkakkar** [comment]
@gnuhel For now, you can use [Jitpack](https://jitpack.io) as outlined in this comment: [Link](https://github.com/vikramkakkar/SublimeNavigationView/issues/2#issuecomment-186410937).

I'll roll out the latest release on gradle in the next few days. Sorry for the inconvenience. Have had my hands full with work :(.

**Comment by gnuhel** [comment]
@vikramkakkar great, will wait for the release. thanks for quick reply
